# Generated by Django 5.0.2 on 2024-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokiBackend", "0003_alter_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(
                choices=[
                    ("work", "work"),
                    ("personal", "personal"),
                    ("coding", "coding"),
                    ("workout", "workout"),
                    ("meeting", "meeting"),
                ],
                db_index=True,
                default="Personal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="priority",
            name="label",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("ASAP", "ASAP"),
                ],
                db_index=True,
                default="Low",
                max_length=10,
            ),
        ),
    ]
