# Generated by Django 6.0.3 on 2026-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokiBackend', '0006_add_due_date_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_focus_block',
            field=models.BooleanField(default=False),
        ),
    ]
