# Generated by Django 5.0.2 on 2024-04-21 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokiBackend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
